name: Run main.py

on:
  workflow_dispatch:  # Puedes activarlo manualmente desde la interfaz de GitHub
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # O la versión que estés usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Write credentials file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run script
        env:
          #GOOGLE_CREDENTIALS_PATH: ./credentials.json  # Ruta relativa en el repo o secrets
        run: |
          python main.py