name: Run main.py

on:
  workflow_dispatch:  # Puedes activarlo manualmente desde la interfaz de GitHub
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ vars.CLIENT_ID }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      TOKEN_URI: ${{ vars.TOKEN_URI }}
      AUTH_PROVIDER_CERT_URL: ${{ vars.AUTH_PROVIDER_CERT_URL }}
      CLIENT_SECRET: ${{ vars.CLIENT_SECRET }}
      TOKEN: ${{ vars.TOKEN }}
      REFRESH_TOKEN: ${{ vars.REFRESH_TOKEN }}
      SCOPES: ${{ vars.SCOPES }}
      UNIVERSE_DOMAIN: ${{ vars.UNIVERSE_DOMAIN }}
      EXPIRY: ${{ vars.EXPIRY }}
      CREDS_FROM_TOKEN: ${{ vars.CREDS_FROM_TOKEN }}
      PERMISSION_EMAILS: ${{ vars.PERMISSION_EMAILS }}
      SEND_NOTIF_EMAIL: ${{ vars.SEND_NOTIF_EMAIL }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # O la versión que estés usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python main.py